---
- name: Paigalda veebiserver AlmaServerisse
  hosts: webservers
  become: true
  tasks:
    - name: Installi Apache (httpd) AlmaLinuxis
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Käivita ja lülita httpd teenus sisse
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

- name: Paigalda andmebaasiserver DebianServerisse
  hosts: dbservers
  become: true
  tasks:
    - name: Uuenda apt paketiindeks
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installi MariaDB server (või MySQL)
      ansible.builtin.apt:
        name: mariadb-server
        state: present

    - name: Käivita ja lülita mariadb teenus sisse
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true
